---
- hosts: localhost
  connection: local
  tasks:
    - name: Create Demo Lab VPC
      ec2_vpc_net:
        name:       "Demo VPC"
        cidr_block: "{{ vpc_cidr_block }}"
        region:     "{{ aws_region }}"
        state:      "present"
      register: demo_vpc

    - name: Get Demo Lab VPC ID
      set_fact:
        vpc_id: "{{ demo_vpc.vpc.id }}"

    - name: Create Demo Lab Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr:   "{{ public_subnet_1_cidr }}"
        az:     "{{ aws_region }}a"
        region: "{{ aws_region }}"
        state:  "present"
      register: public_subnet

    - name: Get Demo Lab Public Subnet ID
      set_fact:
        public_subnet_id: "{{ public_subnet.subnet.id }}"

    - name:               Create Demo Lab Security Group
      ec2_group:
        name:             "Demo Lab"
        description:      "Demo Lab"
        vpc_id:           "{{ vpc_id }}"
        region:           "{{ aws_region }}"
        rules:
          - proto:        "tcp"
            from_port:    "22"
            to_port:      "22"
            cidr_ip:      "{{ my_ip }}/32"
      register: security_group

    - name: Get Demo Lab Security Group
      set_fact:
        group_id: "{{ security_group.group_id }}"

    - name:               Create Internet Gateway for Demo Lab VPC
      ec2_vpc_igw:
        vpc_id:           "{{ vpc_id }}"
        region:           "{{ aws_region }}"
        state:            "present"
      register: my_vpc_igw

    - name:               Get Demo Lab Internet Gateway ID
      set_fact:
        igw_id:           "{{ my_vpc_igw.gateway_id }}"

    - pause: seconds=5

    - name: Set up public subnet route table for Demo Lab Internet Gateway
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags:
          Name: "Public"
        subnets:
          - "{{ public_subnet_id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw_id }}"

    - name: Provision Spark Instances
      ec2:
        region:          "{{ aws_region }}"
        zone:            "{{ aws_region }}a"
        key_name:        "{{ aws_keyname }}"
        instance_type:   "{{ spark_instance_type }}"
        image:           "{{ aws_ami }}"
        wait:            "yes"
        wait_timeout:    "500"
        count:           "{{ spark_instance_count }}"
        volumes:
          - device_name: "/dev/xvda"
            volume_type: "gp2"
            volume_size: "16"
        monitoring:      "yes"
        vpc_subnet_id:   "{{ public_subnet_id }}"
        instance_tags: "group=spark"
        assign_public_ip: "yes"
        group:            "Demo Lab"

    - name: Provision Ceph Instances
      ec2:
        region:         "{{ aws_region }}"
        zone:           "{{ aws_region }}a"
        key_name:       "{{ aws_keyname }}"
        instance_type:  "{{ ceph_instance_type }}"
        image:          "{{ aws_ami }}"
        wait:            "yes"
        wait_timeout:    "500"
        count:           "{{ ceph_instance_count }}"
        volumes:
          - device_name: "/dev/xvda"
            volume_type: "gp2"
            volume_size: "16"
        monitoring:      "yes"
        vpc_subnet_id:   "{{ public_subnet_id }}"
        instance_tags: "group=ceph mon=yes osd=yes rgw=yes"
        assign_public_ip: "yes"
        group:            "Demo Lab"
